### ISSUE TITLE
error on dbt 0.19.1

### ISSUE THREAD

**Issue by danielefrigo** [chop-analytics/dbt-netezza#2]
when upgrading dbt to last version (0.19.1), every command returns this error (even a simple dbt ls):

'int' object has no attribute '_serialize'

**Comment by joemirizio** [comment]
You'll need to make sure the version of the adapter is compatible with your version of `dbt`. If you look in `setup.py` it will tell you what is supported.

I just [released a version](https://github.com/chop-analytics/dbt-netezza/releases/tag/v0.4.0) that is compatible with `dbt` 0.19.1.

**Comment by danielefrigo** [comment]
Thank for your super-quick response!
I noticed that, and it was perfectly working with dbt 0.18.1, but 0.19 has some interesting features so I tried upgrading...

I installed your newer release, but I'm still getting the same error.
Is there anything special I need to do in order to get it working?
I simply installed dbt and your adapter:

pip install dbt
pip install git+https://github.com/chop-analytics/dbt-netezza#egg=dbt-netezza

**Comment by joemirizio** [comment]
Hmm, that should be all you need to do.

I was unable to replicate your error. Can you provide more information? Try running `dbt debug` or using the `--debug` flag with other `dbt` commands.

**Comment by danielefrigo** [comment]
c:\dbt\poc>dbt debug
Running with dbt=0.19.1
dbt version: 0.19.1
python version: 3.8.5
python path: C:\Program Files\Python38\python.exe
os info: Windows-10-10.0.14393-SP0
Using profiles.yml file at C:\Users\sdg\.dbt\profiles.yml
Using dbt_project.yml file at c:\dbt\poc\dbt_project.yml

Error sending message, disabling tracking
Encountered an error:
'int' object has no attribute '_serialize'

**Comment by joemirizio** [comment]
I'm still not sure what that could be other than maybe something in your configuration. Can you try running with a bare-bones project config?

```yml
# --- dbt_project.yml ---
name: dbt_test

config-version: 2
version: 1.0.0

# Replace with your profile name
profile: MYPROFILE
```

You can also use the `--debug` to get more information:
```sh
dbt debug --debug
```

**Comment by danielefrigo** [comment]
I cannot do that right now, I'll try it tomorrow.
In the meantime I can tell you that the project I used for testing is the
one generated by dbt init, and as far as I remember I only changed the
profile name.

Il mar 18 mag 2021, 22:23 Joe Mirizio ***@***.***> ha scritto:

**Comment by danielefrigo** [comment]
```
c:\dbt\poc>dbt --debug debug
2021-05-19 08:19:44.719883 (MainThread): Running with dbt=0.19.1
2021-05-19 08:19:44.719883 (MainThread): running dbt with arguments Namespace(cls=<class 'dbt.task.debug.DebugTask'>, config_dir=False, debug=True, defer=None, log_cache_events=False, log_format='default', partial_parse=None, profile=None, profiles_dir='C:\\Users\\sdg\\.dbt', project_dir=None, record_timing_info=None, rpc_method=None, single_threaded=False, state=None, strict=False, target=None, test_new_parser=False, use_cache=True, use_colors=None, vars='{}', version_check=True, warn_error=False, which='debug', write_json=True)
2021-05-19 08:19:44.719883 (MainThread): Tracking: tracking
2021-05-19 08:19:44.719883 (MainThread): Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'start', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x0000013971A3BA00>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x0000013971A3BAC0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x0000013971A3BA30>]}
dbt version: 0.19.1
python version: 3.8.5
python path: C:\Program Files\Python38\python.exe
os info: Windows-10-10.0.14393-SP0
Using profiles.yml file at C:\Users\sdg\.dbt\profiles.yml
Using dbt_project.yml file at c:\dbt\poc\dbt_project.yml

2021-05-19 08:19:44.766764 (MainThread): Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'end', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x0000013971A1FFA0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x0000013971AD1BE0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x0000013971AD1B80>]}
2021-05-19 08:19:44.766764 (MainThread): Flushing usage events
2021-05-19 08:19:45.282396 (MainThread): Encountered an error:
2021-05-19 08:19:45.282396 (MainThread): 'int' object has no attribute '_serialize'
2021-05-19 08:19:45.282396 (MainThread): Traceback (most recent call last):
  File "C:\Users\sdg\AppData\Roaming\Python\Python38\site-packages\dbt\main.py", line 125, in main
    results, succeeded = handle_and_check(args)
  File "C:\Users\sdg\AppData\Roaming\Python\Python38\site-packages\dbt\main.py", line 203, in handle_and_check
    task, res = run_from_args(parsed)
  File "C:\Users\sdg\AppData\Roaming\Python\Python38\site-packages\dbt\main.py", line 256, in run_from_args
    results = task.run()
  File "C:\Users\sdg\AppData\Roaming\Python\Python38\site-packages\dbt\task\debug.py", line 124, in run
    self.test_configuration()
  File "C:\Users\sdg\AppData\Roaming\Python\Python38\site-packages\dbt\task\debug.py", line 295, in test_configuration
    profile_status = self._load_profile()
  File "C:\Users\sdg\AppData\Roaming\Python\Python38\site-packages\dbt\task\debug.py", line 265, in _load_profile
    profile: Profile = QueryCommentedProfile.render_from_args(
  File "C:\Users\sdg\AppData\Roaming\Python\Python38\site-packages\dbt\config\profile.py", line 423, in render_from_args
    return cls.from_raw_profiles(
  File "C:\Users\sdg\AppData\Roaming\Python\Python38\site-packages\dbt\config\profile.py", line 388, in from_raw_profiles
    return cls.from_raw_profile_info(
  File "C:\Users\sdg\AppData\Roaming\Python\Python38\site-packages\dbt\config\profile.py", line 338, in from_raw_profile_info
    return cls.from_credentials(
  File "C:\Users\sdg\AppData\Roaming\Python\Python38\site-packages\dbt\config\profile.py", line 249, in from_credentials
    profile.validate()
  File "C:\Users\sdg\AppData\Roaming\Python\Python38\site-packages\dbt\config\profile.py", line 141, in validate
    dct = self.credentials.to_dict(omit_none=True)
  File "<string>", line 38, in to_dict
AttributeError: 'int' object has no attribute '_serialize'
```

**Comment by joemirizio** [comment]
This appears to be a profile validation error and isn't going through the adapter. Can you double check your profile?

**Comment by danielefrigo** [comment]
The odd thing is that the same profile works with 0.18.1.
Is there any change I should take into account when moving to 0.19.1?
My profile is very simple:

nz:
  target: dev
  outputs:
    dev:
      type: netezza
      host: AAA
      database: GRADWH_TEST
      schema: ADMIN
      username: XXX
      password: YYY

**Comment by joemirizio** [comment]
AH! The profile requires a `port` and the value we pass as a default isn't the right type. We'll fix this in a future release, but for now, just use:

```yml
nz:
  target: dev
  outputs:
    dev:
      type: netezza
      ...
      port: 5480
```

**Comment by danielefrigo** [comment]
You're absolutely right, adding the port in profile fixes everything!
Odd that in 0.18.1 this was not an issue.
Thank you very much for your help!
